#!/usr/bin/env python3
import json, sys
seen = False
for line in sys.stdin:
    doc = json.loads(line)
    if not seen and doc['SubTest'] == 'upload':
        sys.stdout.write('\n')
        seen = True
    if 'Failure' in doc:
        sys.stdout.write('%10s: %s\n' % (doc['SubTest'], doc['Failure']))
        continue
    speed, unit = 8 * doc['NumBytes'] / doc['ElapsedSeconds'], ' b/s'
    if speed > 1000:
        speed, unit = speed / 1000, 'kb/s'
    if speed > 1000:
        speed, unit = speed / 1000, 'Mb/s'
    if speed > 1000:
        speed, unit = speed / 1000, 'Gb/s'
    sys.stdout.write('%10s: %10.2f %s\r' % (doc['SubTest'], speed, unit))
sys.stdout.write('\n')
